# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://beagle.im
title: Beagle IM by Tigase, Inc.
email: support@tigase.net
author: Tigase, Inc.
description: 'Lightweight and powerful XMPP client for macOS, with audio and video calls and built-in privacy'
copyright: 'Copyright &copy; 2018 Tigase, Inc. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    superclass: b
    class: twitter
    url: https://twitter.com/tigase
  - title: facebook
    superclass: b
    class: facebook
    url: https://www.facebook.com/tigase/
  - title: mastodon
    superclass: b
    class: mastodon
    url: https://mastodon.technology/@tigase
  - title: appstore
    class: download
    url: https://itunes.apple.com/us/app/beagleim-by-tigase-inc/id1445349494?l=pl&ls=1&mt=12
  - title: sourcecode
    superclass: b
    class: github
    url: https://github.com/tigase/beagle-im
  - title: community
    class: comments
    url: https://help.tigase.net
  - title: tasks
    class: tasks
    url: https://projects.tigase.net
